version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "3ncu3st4sBACKEND"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"